--------------------
-- idStrategy tables
--------------------
INSERT INTO SIMPLE_CRUD_AUTO_ID (NAME) VALUES ('simple entity pre inserted with auto id');


--------------------
-- createRepository tables
--------------------
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',1,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',2,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',3,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',4,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',5,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',6,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',7,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',8,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',9,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('A',10,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',1,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',2,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',3,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',4,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',5,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',6,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',7,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',8,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',9,'SAME');
INSERT INTO PAGEABLE_AND_SORTABLE (DISCRIMINATOR, NUMBER, COMMON) VALUES ('B',10,'SAME');




