--Create the table at the startup of the DB

--------------------
-- idStrategy tables
--------------------

CREATE TABLE IF NOT EXISTS SIMPLE_CRUD_AUTO_ID (
   ID IDENTITY NOT NULL PRIMARY KEY,
   NAME varchar(250) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SIMPLE_CRUD_MANUAL_ID_BY_CALL_BACK (
   ID varchar(250) NOT NULL,
   NAME varchar(250) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SIMPLE_CRUD_MANUAL_ID_BY_PERSISTABLE (
   ID varchar(250) NOT NULL,
   NAME varchar(250) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SIMPLE_CRUD_VERSIONED (
   ID IDENTITY NOT NULL PRIMARY KEY,
   NAME varchar(250) NOT NULL,
   VERSION INTEGER,
   PRIMARY KEY (ID)
);

--------------------------
-- createRepository tables
--------------------------

CREATE TABLE IF NOT EXISTS PAGEABLE_AND_SORTABLE (
   ID IDENTITY NOT NULL PRIMARY KEY,
   DISCRIMINATOR varchar(250) NOT NULL,
   NUMBER INTEGER,
   COMMON varchar(250) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CUSTOM (
   ID IDENTITY NOT NULL PRIMARY KEY,
   DATA varchar(250) NOT NULL,
   PRIMARY KEY (ID)
);

---------------------------
-- defineQueryMethod tables
---------------------------

CREATE TABLE IF NOT EXISTS SIMPLE_QUERY_METHOD (
   ID IDENTITY NOT NULL PRIMARY KEY,
   NAME varchar(250) NOT NULL,
   AGE INTEGER,
   BIRTH_DATE  DATE NOT NULL,
   JOB varchar(250) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PROPERTY_EXPRESSIONS_ROOT (
   ID IDENTITY NOT NULL PRIMARY KEY,
   NAME varchar(250) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PROPERTY_EXPRESSIONS_NESTED (
   ID IDENTITY NOT NULL PRIMARY KEY,
   PROPERTY_EXPRESSIONS_ROOT INTEGER,
   ADDRESS varchar(250) NOT NULL,
   PRIMARY KEY (ID)
);

ALTER TABLE PROPERTY_EXPRESSIONS_NESTED
ADD CONSTRAINT FK_PROP_EXPR_ROOT
FOREIGN KEY (PROPERTY_EXPRESSIONS_ROOT)
REFERENCES PROPERTY_EXPRESSIONS_ROOT(ID)
ON DELETE CASCADE;



